// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yLV8ZITfXzwNmV7GGRuE0ljzSdzXUqM',
    appId: '1:895050671303:web:b27f4eda613b84c8aecae2',
    messagingSenderId: '895050671303',
    projectId: 'chyess-c7cad',
    authDomain: 'chyess-c7cad.firebaseapp.com',
    storageBucket: 'chyess-c7cad.appspot.com',
    measurementId: 'G-27HD8GWL2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6EUJofuwCAPYv_B9-537nVkpmi5yQE7U',
    appId: '1:895050671303:android:24079da99d38b3a6aecae2',
    messagingSenderId: '895050671303',
    projectId: 'chyess-c7cad',
    storageBucket: 'chyess-c7cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUUoPeid57gRfVknDb2fQMsX1hFuOM4U',
    appId: '1:895050671303:ios:654e81f28ef8a8deaecae2',
    messagingSenderId: '895050671303',
    projectId: 'chyess-c7cad',
    storageBucket: 'chyess-c7cad.appspot.com',
    iosClientId:
        '895050671303-mvrvqekbvnblrljd2g2e5008dta3e6b7.apps.googleusercontent.com',
    iosBundleId: 'com.chyess',
  );
}
